
spring:
  application:
    name: keycloak-spring-boot-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 123456aA@
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
          jwk-set-uri: http://localhost:8080/realms/ecommerce/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: off
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
