spring:
  application:
    name: keycloak-spring-boot-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 123456aA@
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
          jwk-set-uri: http://localhost:8080/realms/ecommerce/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: off
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: off
  threads:
    virtual:
      enabled: true
#  main:
#    lazy-initialization: false
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: lazy
springdoc:
  swagger-ui:
    syntax-highlight:
      theme: 'monokai'
      activated: true
    display-request-duration: true
    operations-sorter: alpha
  pre-loading-locales:
    - en_US
  pre-loading-enabled: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        enabled: off
